all: wcat wgrep wzip wunzip

wcat:
	gcc -o wcat wcat.c -Wall -Werror

wgrep:
	gcc -o wgrep wgrep.c -Wall -Werror

wzip:
	gcc -o wzip wzip.c -Wall -Werror

wunzip:
	gcc -o wunzip wunzip.c -Wall -Werror

clean:
	$(RM) wcat wgrep wzip wunzip
